/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 jacket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/jacket.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth001.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth002.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth003.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth004.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth005.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth006.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth007.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth008.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth009.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth010.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth011.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth012.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth013.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth014.geometry} material={materials['Cotton_Heavy_Twill Copy 1_FRONT_230423.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth015.geometry} material={materials['Cotton_Heavy_Twill Copy 1_FRONT_230423.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth016.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth017.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth018.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth019.geometry} material={materials['Cotton_Heavy_Twill_FRONT_230413.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth020.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth021.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth022.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth023.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth024.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth025.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth026.geometry} material={materials['Interlining_Polyester_Satin_Lining_FRONT_4715011.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_25991001.geometry} material={materials['Material10559664.002']} />
        <mesh geometry={nodes.MatShape_25991001_1.geometry} material={materials['Material10559665.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26016001.geometry} material={materials['Material10559664.002']} />
        <mesh geometry={nodes.MatShape_26016001_1.geometry} material={materials['Material10559665.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26041001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26041001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26066001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26066001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26091001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26091001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26116001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26116001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26153001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26153001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26190001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26190001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26227001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26227001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.MatShape_26264001.geometry} material={materials['Material11274330.002']} />
        <mesh geometry={nodes.MatShape_26264001_1.geometry} material={materials['Material11274331.002']} />
      </group>
      <mesh geometry={nodes.Cloth027.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth028.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth029.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth030.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth031.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth032.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth033.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth034.geometry} material={materials['PT_FABRIC_FRONT_74083.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth035.geometry} material={materials['PT_FABRIC_FRONT_2628.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cloth036.geometry} material={materials['PT_FABRIC_FRONT_2608.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_983840.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_983883.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_983919.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_983954.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_983981.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_984008.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_984043.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_984079.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.BindedTrim_984102.geometry} material={materials['Material2822.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/jacket.glb')
